### Construção da base de dados
Para esse projeto, o presente notebook tem como objetivo contruir as bases de dados necessárias para aplicação dos métodos nas próximas etapas.

Inicialmente foi pensado em trabalhar apenas com as ações negociadas na B3 (Brasil, Bolsa, Balcão), totalizando 98 ações, possibilitando uma análise mais voltada para o mercado brasileiro. Após tratamento da base e com a exclusão de nulos, o número final de ações operando no período da análise foi de 81.

Entretanto, análises de redes são mais interessantes quando há disponibilidade de mais dados, então foi incluída ações que compõem os índices NASDAQ, NYSE e AMEX. Devido à disponibilidade dos dados a partir do yahoo finance, dos 6414 iniciais, 1111 não foram encontradas, totalizando assim 5303 ações. Após tratamento da base com exclusão de nulos, o número final de ações operando no período de análise foi de 4758. 

Ao final desse notebook, serão construídas duas base de dados, bovespa e nasdaq/nyse para o período de janeiro/2019 a setembro/2022 com dados diários da variação logarítmica diária do preço das ações.

##### Pacotes necessários para instalação:

In [ ]:
#!pip install yfinance --upgrade --no-cache-dir
#!pip install pandas-datareader
#!pip install get-all-tickers

#comentado para não rodar desnecessariamente

O pacote "get-all-tickers" foi necessário para listagem das ações do nasdaq/nyse, porém como a API estava insdisponível, essa lista foi obtida de forma manual a partir de uma junção entre [NASDAQ](https://raw.githubusercontent.com/shilewenuw/get_all_tickers/master/get_all_tickers/tickers.csv) E [NYSE](https://raw.githubusercontent.com/shilewenuw/get_all_tickers/master/get_all_tickers/EU_tickers.csv) encontradas no [repositório Git](https://github.com/shilewenuw/get_all_tickers) do pacote.

PS: Testes realizados para API's anteriores não serão inseridos nesse notebbok apenas as ferramentas utilizadas

In [1]:
#bibliotecas necessárias para desenvolvimento
import pandas as pd
import numpy as np
from pandas_datareader import data as pdr
from bs4 import BeautifulSoup

from get_all_tickers import get_tickers as gt 
import yfinance as yf

import datetime
import time
import requests
import io

##### Dados  Extração dos dados Bovespa e construção do dataframe inicial

In [2]:
df_bovespa = pd.read_csv('base_bovespa.csv', header=None)

In [3]:
bovespa = list(df_bovespa[0])

In [21]:
df_bov = pd.DataFrame()

In [22]:
df = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/VALE3.SA?period1=1546300800&period2=1664496000&interval=1d&events=history&includeAdjustedClose=true')
df_bov['data'] = df['Date']
for ticker in bovespa:
  df = pd.read_csv(f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1=1546300800&period2=1664496000&interval=1d&events=history&includeAdjustedClose=true')
  df_bov[ticker] = df['Close']

##### Extração dos dados NASDAQ/ NYSE e construção do dataframe inicial

In [6]:
df_nasdny = pd.read_csv('base_nasdaq.csv', header=None)

In [7]:
nasdaq = list(df_nasdny[0])

In [24]:
df_nyse_nasdaq = pd.DataFrame()

In [25]:
df_2 = pd.read_csv('https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1546300800&period2=1664496000&interval=1d&events=history&includeAdjustedClose=true')
df_nyse_nasdaq['data'] = df_2['Date']
for ticker in nasdaq:
  try:
    df_2 = pd.read_csv(f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1=1546300800&period2=1664496000&interval=1d&events=history&includeAdjustedClose=true')
    df_nyse_nasdaq[ticker] = df_2['Close']
  except:
    print(ticker)

WBAI
WUBA
AHC
ATV
ADSW
ADS
ALUS
ACC
AFGH
ARA
RYCE
HKIB
PLAN
ANTM
ANH
ARD
AFC
AIW
AFI
AIZP
HOME
ATH
AT
AXO
BMRG
BLL
BXS
BTE
BBX
BBL
BHVN
BITA
BGIO
BFO
BAF
BZM
MHE
BKK
BBK
BBF
MEN
MUH
MFL
MUS
MYF
MFT
BQH
BSE
BFY
BSD
BXG
BCEI
BPMP
BSA
BMY~
COG
CAI
CMD
CSU
CMO
CSPR
CSLT
CBO
CBX
PCPL
CDR
CELG~
CEL
CTL
CHAP
DL
CHL
CHA
CHU
CCX
CCXX
XEC
CBB
CINR
CIT
CCAC
CCC
CLDR
CNXM
MIE
CFX
CFXA
CCH
CLNY
CLNC
CXP
CXO
CCR
CTB
CTK
CLGX
CPLG
COR
CNR
CZZ
CVA
CRY
CUB
CELP
DLPH
DSSI
DNI
DMYT
DCUE
UFS
DVD
DTQ
DSE
DUC
ECCB
EV
EFF
EHT
ENBL
ENIA
ETM
EAB
EAE
EAI
ELJ
EROS
WTRU
ETH
XAN
SFUN
FFG
FOE
FCAU
TCRW
FSLF
FIV
FIT
FLY
FEAC
WPF
FVAC
FBM
FSB
FI
FSKR
GLEO
GLOG
GEN
GIX
GIX~
GIK
GSLD
GMZ
GPX
GRAF
GRAM
GWB
GRUB
GSX
GTT
GSH
GGM
GPM
HGH
HCHC
HTA
PSV
HPR
HRC
HFC
HMI
HNP
HUD
HCFT
INFO
IHC
IPHI
IFFT
IPV
VTA
IRET
IO
JAX
JWS
JCAP
JMP
JIH
JP
KDMN
KSU
KL
KNL
KRA
LB
LAIX
LEAF
LGC
DFNS
LN
LINX
LOAK
LGVW
LUB
LDL
CLI
MIC
MNK
MDLA
MCC
MCV
MDLY
MFAC
MDP
MTOR
MFO
MGP
MBT
MNR
MR
MSGN
MZA
MVC
NTEST
NNA
NAV
NP
NPTN
NSCO
NFH
NWHM
NMFX
NRZ
SNR
NHF
OSB
NCB
JDD
JHY
JHB
NMY
NUM
NHA
NJV
NYV
NPN
NXQ
NXR
JTD
JTA
CTEST
OAC
ONDK
ONE
SFTW
ROYT
PACD
PE
PRSP
PSXP
DNK
PCI
PKO
PIC
PLT
PPX
PQG
PVG
PROS
PBC
PJH
PSB
NEW
QEP
QTS
CTAA
CTY
RRD
RCA
RCP
RLGY
RLH
RPLA
RPAI
RVI
RXN
RMG
RST
RYB
SAIL
PER
SC
SAK
SCPE
SWM
SALT
SCVX
CKH
SERV
WORK
IPOB
IPOC
SOGO
SNE
SJIU
SOLN
SPAQ
FLOW
SCA
STL
SFB
SPN
SOAC
SBE
SYX
TLRD
TCO
TCP
TGP
TDA
TDE
TDI
TDJ
THGA
TPRE
TIF
TSU
SHLL
TOT
TREC
TRNE
GTS
TUFN
TRWH
UN
UZA
UZC
BIF
VAR
VEC
VEDL
VNE
VER
VRS
VSLR
VCRA
IID
IRR
PPR
GRA
WDR
WPG
WEI
WRI
WBT
TLI
MTT
GFY
WBK
WLL
WPX
WYND
GOED
ACY
AUG
BDR
CHAQ
CDOR
MCF
CRHM
VCF
VMM
DPW
FTSI
GMO
GSB
GV
GDP
HMG
IBO
INS
ATEST
NTN
NES
PFNX
TGC
GGO
TAT
TRXC
VOLT
PIH
PIHPP
FCCY
JOBS
JFK
JFKKR
JFKKU
JFKKW
ACIA
ACAM
ACAMU
ACAMW
ACCP
XLRN
ACLL
ADMS
ADILW
ADRO
AEGN
ARPO
AGBAR
AGBAW
AGFSW
AIMT
AIRTW
AKCA
KERNW
AKER
ALSK
ALAC
ALACR
ALACU
ALACW
ALXN
ALTA
ALTM
AMAG
AMCIW
AMTBB
AMRH
AMRHW
AFIN
AFINP
ANAT
AMRB
AVCTW
ASRVP
AMHC
AMHCU
AMHCW
ANCN
ANDA
ANDAR
ANDAU
ANDAW
ATRS
APEX
APXT
APXTU
APXTW
APHA
AINV
ARNA
ARTLW
AACQU
ARYB
ARYBU
ARYBW
ASNA
ASFI
AFH
ATCXW
EARS
CDMOP
AAXN
AXGT
AZRX
BCOM
RILYH
BOCH
ZTEST
BFYT
BRPA
BRPAR
BRPAU
BRPAW
BASI
BCDAW
BFRA
BHTG
BNGOW
BSTC
BLNKW
BLCT
BKEP
BKEPP
BMCH
WIFI
BOKFL
BOMN
BPFH
EPAY
BBRX
BDGE
BRLIR
BRLIW
BROGW
BPY
BPYU
BPYUP
BRKS
BMTC
CCMP
CGIX
CSWCL
CPTA
CPTAG
CPTAL
CPST
CATM
CATB
CBMB
CDK
APOP
APOPW
CLRBZ
CBMG
CETXW
CETV
CNBKA
CERC
CERN
CFFA
CFFAU
CFFAW
CHNGU
CHEKZ
CHFS
CHMA
CBPO
CCCL
CCRC
JRJC
HGSH
PLIN
CHPM
CHPMW
CIIC
CIICU
CIICW
CTXRW
CBLI
CGRO
CGROU
CGROW
CLCT
HHT
CBSHP
JCS
ESXB
CFBI
CDOR
CNST
CPTI
CPAAW
CORE
CSOD
CRTX
CLDB
CPAH
ICBK
COWNZ
BREW
CREXW
CREE
CRSA
CRSAU
CRSAW
CONE
DRIOW
DSKEW
DFHTU
DBCP
DMPI
DRMT
DFPH
DFPHU
DFPHW
DPHC
DPHCU
DPHCW
DRNA
DRAD
DRADP
DISCA
DISCB
DISCK
DHCNL
DLPNW
DSPG
DNKN
ETFC
IGLE
ESSCR
ESSCW
EBAYL
ECHO
EDNT
EIDX
SOLOW
ESBK
ENDP
NDRAW
EIGI
ETTX
ENTXW
EVSI
EVSIW
EPZM
GMBLW
EXFO
EXPC
EXPCU
EXPCW
STAY
EYEG
EYEGW
FLRZ
FB
FLMN
FLMNW
FATBW
FBSS
FDUSG
FDUSL
FDUSZ
FSRV
FSRVU
FSRVW
FTAC
FTACU
FTACW
FEYE
FCBP
INBKL
FMBI
FMBIO
FMBIP
FPRX
FVE
FLXN
FLIR
FLWR
FLDM
FSCT
FRTA
FMCI
FMCIU
FMCIW
FRAN
FORK
FMAX
GARS
GLIBA
GLIBP
GFN
GFNCP
GFNSL
GNMK
GLADL
GOODM
GAINL
GAINM
LANDP
ENT
GBLIL
GBLIZ
GSMGW
GLUU
GMLP
GMLPP
DNJR
GBLK
GHIV
GHIVU
GHIVW
GMHI
GMHIU
GMHIW
GECCL
GEC
GNRSW
GRNV
GRNVR
GRNVU
GRNVW
GDYNW
GSUM
GRIF
GTYH
GFED
GWPH
GWGH
GXGX
GXGXU
GXGXW
HOFVW
HJLI
HJLIW
HWCPL
HCAP
HCAPZ
HYAC
HYACU
HYACW
HDS
HCCO
HCCOU
HCCOW
HTBX
HEBT
HCAC
HCACU
HCACW
MLHR
HX
HCCH
HCCHR
HCCHU
HCCHW
HMSY
TWNKW
HMHC
HWCC
HBMD
HUSN
HEC
HECCU
HECCW
HBANN
HBANO
HBP
HYMCW
ICON
IEC
INFO
IKNX
IMAC
IMACW
ISNS
IMTXW
IMMU
IMRNW
IEAWW
INWK
INOV
INSU
INSUU
INSUW
NTEC
IGICW
XENT
IPLDP
IIN
CMFNL
IRCP
ITMR
JCOM
JMPNZ
KBLM
KBLMR
KBLMU
KBLMW
KBSF
KIN
KTOV
KTOVW
LJPC
LCAHW
LMRK
LMRKN
LMRKO
LMRKP
LAWS
LACQ
LACQU
LACQW
LEVL
LFACW
LLIT
LSAC
LSACU
LSACW
LLNW
LGHLW
LIVK
LIVKU
LIVKW
LIVX
LVGO
LMFAW
LOGM
LONE
LOAC
LOACR
LOACU
LOACW
LORL
LMNX
MFNC
MAGS
MGLN
MJCO
MRLN
MBII
MXIM
MDCA
MFINL
MDGSW
MNLO
MTSL
MCMJ
MCMJW
EBSB
METXW
MCEP
MLND
MIME
MGEN
MSON
MMAC
MWK
MNTA
MKGI
MNCL
MNCLU
MNCLW
MOSY
MTSC
MYL
MYOK
MYOS
NAKD
NK
NESRW
NGHC
NGHCN
NGHCO
NGHCP
NGHCZ
NHLD
NHLDW
NSEC
NTUS
NMCI
NEOS
UEPS
NETE
NFIN
NFINU
NFINW
NTRP
NPA
NPAUU
NPAWW
NYMTP
NEWA
NBAC
NBACR
NBACU
NBACW
NWGI
NEWTI
NXMD
EGOV
NCBS
NKLAW
NBL
NBLX
NOVS
NOVSU
NOVSW
NVUS
NXTD
OMP
OAS
OBLN
OBCI
ODT
OPINI
OFSSI
OFSSL
OCCIP
ONTXW
OPES
OPESU
OPESW
OBAS
ORBC
OEG
ORSN
ORSNR
ORSNU
ORSNW
OSMT
OSN
OTEL
OTG
OTLKW
OXBRW
OXFD
PEIX
PMBC
PAE
PAEWW
PAND
PAVMW
PAVMZ
PCIM
PDLI
PVAC
PNNTG
PBCT
PBCTP
PRCP
PHIOW
PHUNW
PICO
PS
PSTI
PCOM
BPOPN
KCAPL
PPD
PRAH
PFBI
PRVL
PRGX
PRNB
PROG
PFPT
PSACU
PTAC
PTACU
PTACW
PTVCA
PTVCB
PTI
PBIP
PACQ
PACQU
PACQW
PRPLW
QADA
QADB
RRD
RDUS
RAVN
RP
REPH
RBNC
RESN
TORC
RTRX
REXN
RNET
REDU
RIVE
RMRM
ROCH
ROCHU
ROCHW
RUHN
SAFM
SAMAW
SGMS
SHIPW
SHIPZ
EYESW
SLCT
SNCA
SQBG
SREV
SVBI
SGOC
SMED
SHSP
SHLO
SCCI
TYHT
SRRA
SGLB
SGLBW
SSPK
SSPKU
SSPKW
SINA
SINO
SRVA
SMTX
SAQN
SAQNU
SAQNW
SUNS
SNGXW
SOLY
SMMC
SMMCU
SMMCW
SONA
SPKE
SPKEP
STXB
SBPH
SRAC
SRACW
STMP
STND
SBLKZ
STFC
SBBP
SUMR
SNDE
SNSS
SCON
SPRT
SVMK
SYKE
SYNC
SYNL
TLC
TLND
THWWW
TCF
TCFCP
TNAV
TLGT
TZAC
TZACU
TZACW
TCBIL
TCBIP
MEET
MIK
PECK
PRSC
TXAC
THBR
THBRU
THBRW
TVTY
TRCH
TOTA
TOTAR
TOTAU
TOTAW
CLUB
TWMC
TBIO
TRMT
TPCO
TDAC
TDACU
TDACW
TRIL
TSC
TSCAP
TSCBP
TPTX
THCB
THCBU
THCBW
THCAW
USCR
USWSW
LATN
LATNU
LATNW
UMRX
MYT
UROV
ECOLW
VTEC
VERBW
VRMEW
VIAC
VIACA
VIE
VKTXW
VRTU
VG
WSG
WTREP
WNFM
FREEW
WLTW
WINS
WRTC
WMGI
XLNX
XPER
YIN
YRCW
ZGYH
ZGYHR
ZGYHU
ZGYHW
ZAGG
ZN
ZNWAA
ZIONN
ZIOP
ZIXI
ZGNX
ZSAN
ZNGA

Como o processo de coleta dos dados e montagem do dataframe nasdaq demora em torno de 1:30 hora e também para facilitar a importação dos dados nas próximas etapas, será armazenado o csv com os dados finais para a leituras posteriores.

In [29]:
df_bov.to_csv('df_bov.csv', index=False)

In [30]:
df_nyse_nasdaq.to_csv('df_nn.csv', index=False)

In [54]:
#leitura dos dados
df_nn = pd.read_csv('df_nn.csv')
df_bov = pd.read_csv('df_bov.csv')

##### Descritivas das bases originais com os preços de fechamento das ações

In [33]:
df_bov.describe()

,RRRP3.SA,ALPA4.SA,ABEV3.SA,AMER3.SA,ASAI3.SA,AZUL4.SA,B3SA3.SA,BPAN4.SA,BBSE3.SA,BRML3.SA,...,VIVT3.SA,TIMS3.SA,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VIIA3.SA,VBBR3.SA,WEGE3.SA,YDUQ3.SA
count,466.000000,931.000000,931.000000,931.000000,398.000000,931.000000,931.000000,931.000000,931.000000,931.000000,...,931.000000,931.000000,931.000000,931.000000,931.000000,931.000000,931.000000,931.000000,931.000000,931.000000
mean,37.455558,31.081796,15.855929,53.584361,15.851156,33.539065,14.840136,9.953330,27.148947,11.002718,...,46.186445,13.032879,25.365016,18.487454,11.572793,70.015038,9.262148,23.275059,26.043996,28.535929
std,5.530982,11.357765,2.094674,26.775636,1.935715,12.845578,3.059224,4.858988,4.479937,2.863705,...,3.524025,1.329325,7.586571,4.270738,4.350807,21.810795,5.314401,3.492386,10.822329,8.819823
min,20.799999,13.888000,11.030000,12.540000,11.300000,10.350000,9.263333,1.940000,18.400000,6.970000,...,40.000000,10.540000,9.405462,10.690000,3.800000,34.099998,1.830000,13.740000,8.725000,10.780000
25%,34.235000,21.630001,14.455000,32.434986,14.557000,22.490000,12.273333,7.390000,23.920000,8.850000,...,43.480000,12.070000,19.333332,14.395000,8.400000,50.899999,4.505000,21.149999,15.145000,23.130000
50%,37.260000,29.080000,15.600000,47.650002,15.936000,35.669998,14.490000,9.360000,26.719999,9.950000,...,45.500000,12.780000,26.459999,18.950001,10.040000,63.340000,7.750000,22.840000,29.100000,28.350000
75%,41.312501,38.950001,17.559999,70.750396,17.414500,42.250000,17.165000,10.920000,29.469999,13.205000,...,48.935000,13.745000,30.814999,21.190001,14.750000,87.254998,14.065000,26.260000,34.917499,33.370001
max,49.310001,61.220001,20.629999,126.000000,19.490000,62.410000,22.466665,25.580000,38.320000,19.219999,...,56.740002,17.490000,40.599998,29.094999,23.570000,118.720001,21.290001,31.090000,46.105000,56.599998

In [32]:
df_nn.describe()

,DDD,MMM,EGHT,AOS,ATEN,AIR,AAN,ABB,ABT,ABBV,...,ZIONO,ZIONP,ZKIN,ZM,ZI,ZVO,ZS,ZUMZ,ZYNE,ZYXI
count,944.000000,944.000000,944.000000,944.000000,944.000000,944.000000,464.000000,944.000000,944.000000,944.000000,...,944.000000,944.000000,944.000000,870.000000,586.000000,873.000000,944.000000,944.000000,944.000000,944.000000
mean,14.842309,169.620985,19.595498,56.741144,9.752691,35.866197,22.848685,26.680678,102.425900,104.522627,...,26.865286,23.300710,2.117532,208.950787,49.574249,2.632971,147.526949,33.182617,4.922600,10.655803
std,9.384484,21.746657,7.573222,11.360161,3.405589,9.156746,5.987778,6.347823,18.223763,26.044473,...,1.151132,1.936689,1.700766,130.282330,9.869007,1.527620,83.010525,9.040448,3.070345,4.214436
min,4.650000,112.300003,3.480000,34.750000,3.520000,9.440000,10.510000,14.850000,62.820000,62.980000,...,19.430000,16.500000,0.690000,62.000000,31.049999,0.151000,39.320000,14.520000,0.782000,2.563636
25%,8.305000,155.139996,15.657500,47.619999,6.920000,32.927499,18.959999,20.122499,84.949997,83.169998,...,26.180000,21.723850,1.230000,93.715002,42.165000,1.450000,67.715000,25.497500,3.410000,7.620000
50%,10.805000,169.550003,19.645001,54.815000,8.305000,37.914999,22.229999,26.540001,106.285000,99.444999,...,27.110001,23.952200,1.430000,155.744996,48.135000,2.350000,144.139999,31.399999,4.180000,9.700000
75%,21.250000,181.792496,24.035000,65.922499,13.352500,42.227501,26.832500,32.607499,118.265000,117.127501,...,27.639999,24.966551,2.250000,324.614990,55.435000,3.790000,207.794994,42.072501,5.602500,13.411364
max,55.349998,219.500000,38.130001,85.849998,18.690001,52.349998,37.150002,39.000000,141.460007,174.960007,...,29.420000,26.850000,12.350000,568.340027,77.349998,6.790000,368.779999,54.630001,15.500000,25.981817

### Transformação dos dados

#### Limpeza da base

Diversas empresas realizaram o IPO (Initial Public Offering ou oferta pública inicial) após a data inicial escolhida, ou seja, essas empresas passaram a ser de capital aberto com ações negociadas na Bolsa de Valores apenas após o período escolhido e portanto não possui informações suficientes para análise. Também há casos onde a empresa parou de negociar na bolsa ou mesmo não há informações disponíveis na fonte de dados para determinados períodos. 

Dessa forma, optou-se por excluir as ações com essas características. Nesse caso, se aplica à colunas que possuir mais de 60 linhas com informações nulas.

#### BOVESPA

In [34]:
print(df_bov.isnull().sum())

data          0
RRRP3.SA    465
ALPA4.SA      0
ABEV3.SA      0
AMER3.SA      0
           ...
VALE3.SA      0
VIIA3.SA      0
VBBR3.SA      0
WEGE3.SA      0
YDUQ3.SA      0
Length: 91, dtype: int64

In [35]:
df_bov.shape

(931, 91)

In [39]:
colunas = df_bov.columns
df_bv = df_bov.copy()
for coluna in colunas:
    if df_bov[coluna].isnull().sum() > 60:
        df_bv = df_bv.drop(coluna, axis=1)

In [65]:
df_bv.shape

(931, 81)

In [49]:
df_bv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 81 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   data       931 non-null    object
 1   ALPA4.SA   931 non-null    float64
 2   ABEV3.SA   931 non-null    float64
 3   AMER3.SA   931 non-null    float64
 4   AZUL4.SA   931 non-null    float64
 5   B3SA3.SA   931 non-null    float64
 6   BPAN4.SA   931 non-null    float64
 7   BBSE3.SA   931 non-null    float64
 8   BRML3.SA   931 non-null    float64
 9   BBDC3.SA   931 non-null    float64
 10  BBDC4.SA   931 non-null    float64
 11  BRAP4.SA   931 non-null    float64
 12  BBAS3.SA   931 non-null    float64
 13  BRKM5.SA   931 non-null    float64
 14  BRFS3.SA   931 non-null    float64
 15  BPAC11.SA  931 non-null    float64
 16  CRFB3.SA   931 non-null    float64
 17  CCRO3.SA   931 non-null    float64
 18  CMIG4.SA   931 non-null    float64
 19  CIEL3.SA   931 non-null    float64
 20  COGN3.SA   931 non-null    float64
 21  CPLE6.SA   931 non-null    float64
 22  CSAN3.SA   931 non-null    float64
 23  CPFE3.SA   931 non-null    float64
 24  CVCB3.SA   931 non-null    float64
 25  CYRE3.SA   931 non-null    float64
 26  DXCO3.SA   931 non-null    float64
 27  ECOR3.SA   931 non-null    float64
 28  ELET3.SA   931 non-null    float64
 29  ELET6.SA   931 non-null    float64
 30  EMBR3.SA   931 non-null    float64
 31  ENBR3.SA   931 non-null    float64
 32  ENGI11.SA  931 non-null    float64
 33  ENEV3.SA   931 non-null    float64
 34  EGIE3.SA   931 non-null    float64
 35  EQTL3.SA   931 non-null    float64
 36  EZTC3.SA   931 non-null    float64
 37  FLRY3.SA   931 non-null    float64
 38  GGBR4.SA   931 non-null    float64
 39  GOAU4.SA   931 non-null    float64
 40  GOLL4.SA   931 non-null    float64
 41  HAPV3.SA   931 non-null    float64
 42  HYPE3.SA   931 non-null    float64
 43  IRBR3.SA   931 non-null    float64
 44  ITSA4.SA   931 non-null    float64
 45  ITUB4.SA   931 non-null    float64
 46  JBSS3.SA   931 non-null    float64
 47  JHSF3.SA   931 non-null    float64
 48  KLBN11.SA  931 non-null    float64
 49  RENT3.SA   931 non-null    float64
 50  LREN3.SA   931 non-null    float64
 51  MGLU3.SA   931 non-null    float64
 52  MRFG3.SA   931 non-null    float64
 53  BEEF3.SA   931 non-null    float64
 54  MRVE3.SA   931 non-null    float64
 55  MULT3.SA   931 non-null    float64
 56  PCAR3.SA   931 non-null    float64
 57  PETR3.SA   931 non-null    float64
 58  PETR4.SA   931 non-null    float64
 59  PRIO3.SA   931 non-null    float64
 60  POSI3.SA   931 non-null    float64
 61  QUAL3.SA   931 non-null    float64
 62  RADL3.SA   931 non-null    float64
 63  RAIL3.SA   931 non-null    float64
 64  SBSP3.SA   931 non-null    float64
 65  SANB11.SA  931 non-null    float64
 66  CSNA3.SA   931 non-null    float64
 67  SLCE3.SA   931 non-null    float64
 68  SULA11.SA  931 non-null    float64
 69  SUZB3.SA   931 non-null    float64
 70  TAEE11.SA  931 non-null    float64
 71  VIVT3.SA   931 non-null    float64
 72  TIMS3.SA   931 non-null    float64
 73  TOTS3.SA   931 non-null    float64
 74  UGPA3.SA   931 non-null    float64
 75  USIM5.SA   931 non-null    float64
 76  VALE3.SA   931 non-null    float64
 77  VIIA3.SA   931 non-null    float64
 78  VBBR3.SA   931 non-null    float64
 79  WEGE3.SA   931 non-null    float64
 80  YDUQ3.SA   931 non-null    float64
dtypes: float64(80), object(1)
memory usage: 589.3+ KB

In [48]:
colunas1 = df_bv.columns
for coluna in colunas1:
    if df_bv[coluna].isnull().sum() > 0:
        print(coluna)

#### NASDAQ/NYSE

In [55]:
print(df_nn.isnull().sum())

data     0
DDD      0
MMM      0
EGHT     0
AOS      0
        ..
ZVO     71
ZS       0
ZUMZ     0
ZYNE     0
ZYXI     0
Length: 5299, dtype: int64

In [56]:
df_nn.shape

(944, 5299)

In [57]:
colunasn = df_nn.columns
df_n = df_nn.copy()
for coluna in colunasn:
    if df_nn[coluna].isnull().sum() > 60:
        df_n = df_n.drop(coluna, axis=1)

In [58]:
df_n.shape

(944, 4758)

In [60]:
df_bv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 931 entries, 0 to 930
Data columns (total 81 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   data       931 non-null    object
 1   ALPA4.SA   931 non-null    float64
 2   ABEV3.SA   931 non-null    float64
 3   AMER3.SA   931 non-null    float64
 4   AZUL4.SA   931 non-null    float64
 5   B3SA3.SA   931 non-null    float64
 6   BPAN4.SA   931 non-null    float64
 7   BBSE3.SA   931 non-null    float64
 8   BRML3.SA   931 non-null    float64
 9   BBDC3.SA   931 non-null    float64
 10  BBDC4.SA   931 non-null    float64
 11  BRAP4.SA   931 non-null    float64
 12  BBAS3.SA   931 non-null    float64
 13  BRKM5.SA   931 non-null    float64
 14  BRFS3.SA   931 non-null    float64
 15  BPAC11.SA  931 non-null    float64
 16  CRFB3.SA   931 non-null    float64
 17  CCRO3.SA   931 non-null    float64
 18  CMIG4.SA   931 non-null    float64
 19  CIEL3.SA   931 non-null    float64
 20  COGN3.SA   931 non-null    float64
 21  CPLE6.SA   931 non-null    float64
 22  CSAN3.SA   931 non-null    float64
 23  CPFE3.SA   931 non-null    float64
 24  CVCB3.SA   931 non-null    float64
 25  CYRE3.SA   931 non-null    float64
 26  DXCO3.SA   931 non-null    float64
 27  ECOR3.SA   931 non-null    float64
 28  ELET3.SA   931 non-null    float64
 29  ELET6.SA   931 non-null    float64
 30  EMBR3.SA   931 non-null    float64
 31  ENBR3.SA   931 non-null    float64
 32  ENGI11.SA  931 non-null    float64
 33  ENEV3.SA   931 non-null    float64
 34  EGIE3.SA   931 non-null    float64
 35  EQTL3.SA   931 non-null    float64
 36  EZTC3.SA   931 non-null    float64
 37  FLRY3.SA   931 non-null    float64
 38  GGBR4.SA   931 non-null    float64
 39  GOAU4.SA   931 non-null    float64
 40  GOLL4.SA   931 non-null    float64
 41  HAPV3.SA   931 non-null    float64
 42  HYPE3.SA   931 non-null    float64
 43  IRBR3.SA   931 non-null    float64
 44  ITSA4.SA   931 non-null    float64
 45  ITUB4.SA   931 non-null    float64
 46  JBSS3.SA   931 non-null    float64
 47  JHSF3.SA   931 non-null    float64
 48  KLBN11.SA  931 non-null    float64
 49  RENT3.SA   931 non-null    float64
 50  LREN3.SA   931 non-null    float64
 51  MGLU3.SA   931 non-null    float64
 52  MRFG3.SA   931 non-null    float64
 53  BEEF3.SA   931 non-null    float64
 54  MRVE3.SA   931 non-null    float64
 55  MULT3.SA   931 non-null    float64
 56  PCAR3.SA   931 non-null    float64
 57  PETR3.SA   931 non-null    float64
 58  PETR4.SA   931 non-null    float64
 59  PRIO3.SA   931 non-null    float64
 60  POSI3.SA   931 non-null    float64
 61  QUAL3.SA   931 non-null    float64
 62  RADL3.SA   931 non-null    float64
 63  RAIL3.SA   931 non-null    float64
 64  SBSP3.SA   931 non-null    float64
 65  SANB11.SA  931 non-null    float64
 66  CSNA3.SA   931 non-null    float64
 67  SLCE3.SA   931 non-null    float64
 68  SULA11.SA  931 non-null    float64
 69  SUZB3.SA   931 non-null    float64
 70  TAEE11.SA  931 non-null    float64
 71  VIVT3.SA   931 non-null    float64
 72  TIMS3.SA   931 non-null    float64
 73  TOTS3.SA   931 non-null    float64
 74  UGPA3.SA   931 non-null    float64
 75  USIM5.SA   931 non-null    float64
 76  VALE3.SA   931 non-null    float64
 77  VIIA3.SA   931 non-null    float64
 78  VBBR3.SA   931 non-null    float64
 79  WEGE3.SA   931 non-null    float64
 80  YDUQ3.SA   931 non-null    float64
dtypes: float64(80), object(1)
memory usage: 589.3+ KB

#### Transformação dos preços

A base coletada possui o preço de fechamento das ações mas segundo *Mantegna e Stanley* (2000, p.98) para trabalhar com detecção de similaridades e diferenças ao longo do tempo entre ações de mercado financeiro é estudar o coeficiente de correlação entre as mudanças logarítmicas diárias no preço de dessas ações.

Para isso, podemos definir essas mudanças como: 

$$ S_i \equiv ln Y_i(t) - ln Y_i (t-1)$$

Dessa forma, segue a transformação das bases de dados com preço de fechamento para mudanças logarítmicas do preço

##### BOVESPA

In [70]:
colunast = df_bv.columns 
colunast = list(colunast)[1:]
df_b = pd.DataFrame()
df_b['data'] = df_bv['data']

In [93]:
for c in colunast:
    df_b[c] = np.log(df_bv[c])
    df_b[c] = df_b[c].diff()

In [96]:
df_b.head()

,data,ALPA4.SA,ABEV3.SA,AMER3.SA,AZUL4.SA,B3SA3.SA,BPAN4.SA,BBSE3.SA,BRML3.SA,BBDC3.SA,...,VIVT3.SA,TIMS3.SA,TOTS3.SA,UGPA3.SA,USIM5.SA,VALE3.SA,VIIA3.SA,VBBR3.SA,WEGE3.SA,YDUQ3.SA
0,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-03,0.001713,0.011084,0.010181,0.001100,0.042620,-0.030459,0.010887,0.006664,0.020203,...,-0.012244,-0.019112,0.022775,-0.018762,-0.021751,-0.041768,-0.016111,0.022815,0.022547,-0.000805
2,2019-01-04,-0.007443,0.013382,-0.033711,-0.003305,-0.036879,0.015346,-0.009828,-0.019375,-0.022162,...,-0.007516,0.005021,0.027261,-0.006773,0.056984,0.063071,-0.009324,0.003752,0.011355,0.015188
3,2019-01-07,-0.002301,-0.004239,-0.045296,-0.026556,-0.005381,-0.010204,-0.014926,-0.006038,0.008368,...,0.002673,0.032036,-0.021817,-0.031061,0.001976,-0.005379,-0.007051,0.005602,-0.015714,-0.020033
4,2019-01-08,0.019396,-0.020227,0.045296,-0.016567,0.002874,0.000000,-0.014788,0.001513,0.011050,...,-0.022087,0.037291,-0.041572,-0.016692,-0.036185,0.009586,-0.048319,-0.034094,-0.008226,0.009265

##### NASDAQ/NYSE

In [97]:
colunastt = df_n.columns 
colunastt = list(colunastt)[1:]
df_ny = pd.DataFrame()
df_ny['data'] = df_n['data']

In [98]:
for c in colunastt:
    df_ny[c] = np.log(df_n[c])
    df_ny[c] = df_ny[c].diff()

In [100]:
df_ny.head()

,data,DDD,MMM,EGHT,AOS,ATEN,AIR,ABB,ABT,ABBV,...,ZG,ZION,ZIONL,ZIONO,ZIONP,ZKIN,ZS,ZUMZ,ZYNE,ZYXI
0,2019-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-03,-0.052049,-0.038381,-0.017007,-0.024451,-0.031125,-0.021866,-0.020203,-0.048344,-0.033504,...,-0.010933,-0.005547,0.000000,0.001177,0.019162,-0.065133,-0.012385,-0.013340,-0.013532,-0.024520
2,2019-01-04,0.037591,0.040317,0.060456,0.039293,0.024652,0.025065,0.035351,0.028142,0.031709,...,0.025975,0.030251,-0.005670,0.012858,0.011025,0.126881,0.060445,0.024995,0.086103,0.045068
3,2019-01-07,0.051099,-0.002302,0.046275,0.017747,0.008084,0.012695,-0.003636,0.014865,0.014490,...,0.005503,0.003981,0.013414,0.004635,0.008929,0.017805,0.041961,0.046268,0.000000,0.003384
4,2019-01-08,0.006437,0.004182,0.020347,0.024198,0.039468,0.025429,0.014463,-0.012079,0.004637,...,0.026439,0.009073,0.000000,0.013017,-0.000196,-0.092373,0.009596,0.014327,0.029559,-0.006780

Terminada a transformação dos dados, esses serão os csv's salvos para que poassam ser trabalhados nas próximas etapas do projeto:

In [95]:
df_b.to_csv('df_b.csv', index=False)

In [101]:
df_ny.to_csv('df_ny.csv', index=False)

### Referências:

[1] MANTEGNA, Rosario N.; STANLEY, H. Eugene. An Introduction to Econophysics Correlation and Complexity in Finance, Cambridge University Press, Cambridge, 2000.